header:
  version: 11

machine: bbb
distro: mominux
target:
  - kiss-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: kirkstone
    layers:
      meta:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    branch: kirkstone
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-kiss:
    layers:
      meta-kiss:
  
  meta-openembedded:
    url: git://git.openembedded.org/meta-openembedded
    branch: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  meta-qt:
    url: https://github.com/meta-qt5/meta-qt5.git
    branch : kirkstone

local_conf_header:
  meta-kiss: |
    # Some useful lines you may want to copy to your site.conf for development
    INHERIT += "rm_work"
    EXTRA_IMAGE_FEATURES = "debug-tweaks"
    DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

    DISTRO_FEATURES:append = " systemd"
    #TMPDIR = "kas_custom_bbb"
    DL_DIR ?= "${HOME}/workspace/embeddedlinux/yocto/bitbake.downloads"
    SSTATE_DIR ?= "${HOME}/workspace/embeddedlinux/yocto/bitbake.sstate"